---
apiVersion: v1
kind: Namespace
metadata:
  name: gfs-demo

---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: gfs-demo
  labels:
    name: redis
spec:
  containers:
    - name: redis
      image: redis
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: '/mnt/gluster'
          name: glusterfscsivol
  volumes:
    - name: glusterfscsivol
      persistentVolumeClaim:
        claimName: gfs-demo

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-demo
  labels:
    name: gfs-demo
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  claimRef:
    name: gfs-demo
    namespace: gfs-demo
  csi:
    driver: gluster-csi
    volumeHandle: dashboard
    volumeAttributes:
      server: gfs.host.net
      volume: /dashboard

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gfs-demo
  namespace: gfs-demo
  labels:
    name: gfs-demo
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
