---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: gluster-csi
spec:
  attachRequired: false
  podInfoOnMount: false
  volumeLifecycleModes:
    - Persistent

---
apiVersion: v1
kind: Namespace
metadata:
  name: glusterfs-csi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: glusterfs-csi
  namespace: glusterfs-csi

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: glusterfs-csi-nodeplugin
  namespace: glusterfs-csi
spec:
  selector:
    matchLabels:
      app: glusterfs-csi-nodeplugin
  template:
    metadata:
      labels:
        app: glusterfs-csi-nodeplugin
    spec:
      serviceAccount: glusterfs-csi
      hostNetwork: true
      tolerations:
        - operator: Exists
      containers:
        - name: csi-node-driver-registrar
          image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
          args:
            - '--v=5'
            - '--csi-address=$(ADDRESS)'
            - '--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)'
          env:
            - name: ADDRESS
              value: /plugin/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins_registry/glusterfs-csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: registration-dir
              mountPath: /registration
        - name: glusterfs-csi
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          image: ghcr.io/homelab-library/glusterfs-csi
          args:
            - '--nodeid=$(NODE_ID)'
            - '--endpoint=$(CSI_ENDPOINT)'
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
          imagePullPolicy: 'Always'
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: 'Bidirectional'
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/glusterfs-csi
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: glusterfs-csi
  namespace: glusterfs-csi
rules:
  - apiGroups: ['']
    resources: ['persistentvolumes']
    verbs: ['get', 'list', 'watch', 'update', 'create', 'delete']
  - apiGroups: ['']
    resources: ['nodes']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources: ['persistentvolumeclaims']
    verbs: ['get', 'list', 'watch', 'update']
  - apiGroups: ['storage.k8s.io']
    resources: ['storageclasses']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['storage.k8s.io']
    resources: ['volumeattachments']
    verbs: ['get', 'list', 'watch', 'update']
  - apiGroups: ['']
    resources: ['events']
    verbs: ['list', 'watch', 'create', 'update', 'patch', 'delete', 'get']
  - apiGroups: ['csi.storage.k8s.io']
    resources: ['csinodeinfos']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['get', 'list']
  - apiGroups: ['']
    resources: ['endpoints']
    verbs: ['get', 'list', 'watch', 'create', 'update']
  - apiGroups: ['snapshot.storage.k8s.io']
    resources: ['volumesnapshotclasses']
    verbs: ['get', 'list', 'watch']
  - apiGroups: ['snapshot.storage.k8s.io']
    resources: ['volumesnapshotcontents']
    verbs: ['create', 'get', 'list', 'watch', 'update', 'delete']
  - apiGroups: ['snapshot.storage.k8s.io']
    resources: ['volumesnapshots']
    verbs: ['get', 'list', 'watch', 'update']
  - apiGroups: ['apiextensions.k8s.io']
    resources: ['customresourcedefinitions']
    verbs: ['create', 'list', 'watch', 'delete']
  - apiGroups: ['csi.storage.k8s.io']
    resources: ['csidrivers']
    verbs: ['create', 'delete']

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: glusterfs-csi-role
  namespace: glusterfs-csi
subjects:
  - kind: ServiceAccount
    name: glusterfs-csi
    namespace: glusterfs-csi
roleRef:
  kind: ClusterRole
  name: glusterfs-csi
  apiGroup: rbac.authorization.k8s.io
