name: Build CSI Binary

on:
  push:
    branches: [master]

jobs:
  gluster-csi:
    name: Create GlusterFS CSI Binary
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - platform: linux/amd64
          - platform: linux/arm/v7
          - platform: linux/arm64

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build CSI binary
        run: |-
          mkdir -p dist

          docker buildx build \
            --platform ${{ matrix.platform }} \
            -f .github/scripts/csibuild.dockerfile \
            -t csibuilder --load .            

          docker run -u $UID:$UID \
            -v $PWD/dist:/dist csibuilder \
              cp /go/src/gluster/gluster-csi /dist/

          tar -cvz -C dist/ gluster-csi -f $PWD/gluster-csi.tar.gz
