name: Build Container

on:
  push:
    branches: [master]

jobs:
  docker_images:
    name: Create GlusterFS Container
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.GHCR_USER }}
          DOCKER_PASSWORD: ${{ secrets.GHCR_TOKEN }}
        run: |-
          docker login ghcr.io -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

      - name: Run Crossbuild
        run: |-
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            -t "ghcr.io/homelab-library/glusterfs-csi:latest" \
            --push .
