name: Build GlusterFS Packages

on:
  push:
    branches: [master]

jobs:
  glusterfs:
    name: Custom GlusterFS Package
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        include:
          - platform: linux/amd64
            tag: amd64
          - platform: linux/arm/v7
            tag: arm
          - platform: linux/arm64
            tag: arm64

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build CSI binary
        run: |-
          mkdir -p out

          docker buildx build \
            --platform ${{ matrix.platform }} \
            -f .github/scripts/gfsbuild.dockerfile \
            -t gfsbuilder --load .            

          docker run -u $UID:$UID \
            -v $PWD/out:/out gfsbuilder \
              cp -r /dist/ /out/

          tar -cJ -C dist/ gluster-csi -f $PWD/gluster-csi.tar.xz
